version: '3'


services:
  app:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
    ports:
      - 8000:8000
    env_file:
      - .env

  db:
    image: postgres:11-alpine
    environment:
      - NAME=new_blog-02
      - USER=postgres
      - PASSWORD=yusuf123

    volumes:
      - .:/code


