version: '3.10.5'


services:
  app:
    build: .
    command: python manage.py runserver 
    depends_on:
      - db
    links:
      - db:db
    ports:
      - "8000:8000"
    env_file:
      - .env

  db:
    image: postgres:14.4
    environment:
      - POSTGRES_DB=new_blog-02
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=yusuf123

    volumes:
      - .:/code

# version: "3.8"

# services:
#   db:
#     image: postgres:10
#     container_name: db
#     environment:
#       - POSTGRES_DB=new_blog-02
#       - POSTGRES_USER=postgres
#       - POSTGRES_PASSWORD=yusuf123
#     volumes:
#       - .:/code

  
#   app:
#     build: .
#     container_name: Blog
#     command: python manage.py runserver 0.0.0.0:8000
#     depends_on:
#       - db
#     ports:
#       - "8000:8000"
#     env_file:
#       - .env
