# Generated by Django 4.0.3 on 2022-04-11 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='address',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
    ]
